### ISSUE TITLE
Options to skip data that has been already segmented. 

### ISSUE THREAD

**Issue by ChengranAA** [clementpoiret/HSF#27]
Hi there; 

Currently, I can only prepare the full dataset and segment everything. Is there a way to skip subjects that have already been segmented? This would be really helpful to avoid duplicate segmentation.

Thank you for considering adding this feature or for any recommendations on how to proceed with this in the current version.

**Comment by clementpoiret** [comment]
Hi!
That's true that you can't really filter out subs who already have their segmentations. That a feature I can definitely add, thanks for the suggestion!
In the meantime, and that's what I do, I simply have this workflow:

- One main folder (let's call it f1) containing the raw data with segmentations,
- One temporary folder (f2) containing images to be segmented,
- I run HSF in f2,
- Perform a small visual QC of the results,
- For all subs that have correct segmentation, move them to f1 for future analysis.

**Comment by clementpoiret** [comment]
This feature is now merged into master. I am doing some minor fixes. You should be able to update hsf to v1.2.1 later this day.

**Comment by ChengranAA** [comment]
Thank you very much!
